rootProject.name = "delivery"
include(
    "libs:crypto",
    "libs:messages"
)
include("monitor")
include(
    "backend:authentication",
    "backend:store",
    "backend:fms"
)
include(
    "robot:hmi",
    "robot:motion",
    "robot:locker",
    "robot:sensors",
    "robot:positioning_driver",
    "robot:odometer",
    "robot:location",
    "robot:central",
    "robot:communication"
)
