@startuml
!pragma teoz true
'autonumber

participant "Central control\n unit" as CCU
participant "Motion control\n unit" as MCU
participant "Positioning\n unit" as PU
participant "Locker\n unit" as LU
actor "Attacker" as Att #red

activate CCU
note over CCU: in process of delivery

loop go to user until destination reached

PU      -> CCU:     current position
Att     -[#red]> CCU: control

note over CCU #red: navigate using external target

CCU     -[#red]> MCU:     invalid target driving\n speed & direction

end

note over CCU #red: arrived at unknown point =>\n  robot lost physically

opt try opening locker
CCU     -[#red]> LU:      open locker
note over CCU #red: successfully opened because\nthe location is valid for CCU
end

deactivate CCU


@enduml