@startuml
!pragma teoz true
'autonumber

actor "Attacker" as Att #red
participant "Fleet management\n service" as FMS
participant "Central control\n unit" as CCU
participant "Motion control\n unit" as MCU

FMS -> CCU: new task

activate CCU

opt
note over CCU #red: do not validate signature and decrypt pin

else

Att -[#red]> CCU: other delivery details
note over CCU #red: change task description to attacker's

end

loop#red
CCU -[#red]> CCU: navigate to attacker's destination
CCU -[#red]> MCU: directions to false target
end

deactivate CCU


@enduml