@startuml
!pragma teoz true
'autonumber

actor "Attacker" as Att #red
participant "Central control\n unit" as CCU
participant "Sensors\n unit" as SU
participant "Locker\n unit" as LU
participant "Human-machine\n interface unit" as HMI
actor "User" as User

alt control of locker

Att -[#red]> LU: open
activate LU

LU -[#red]> LU: open
note over LU #red: opened => contents stolen

deactivate LU

else no notification of human
note over CCU: arrived at destination
User -> HMI: enter pin
&HMI -> CCU: pin
note over SU #red: no user arrived notification
note over CCU #red: pin attempt ignored as no user present

end


@enduml