@startuml
!pragma teoz true
'autonumber

participant "Fleet management\n service" as FMS
participant "Central control\n unit" as CCU
participant "Human-machine\n interface unit" as HMI
actor "User" as User

FMS -> CCU: new task

activate CCU
note over CCU: arrived to destination

loop#red more that allowed pin enter attempts
HMI -> CCU: pin enter request
note over CCU #red: infinitely waiting\n for valid pin

else

FMS -> CCU: new task
note over CCU: previous task not finished
CCU --[#red]> FMS: already in progress

end

note over FMS #red: robot lost

@enduml