@startuml
!pragma teoz true
'autonumber

participant "Central control\n unit" as CCU
participant "Motion control\n unit" as MCU
participant "Positioning\n unit" as PU
participant "Odometer Positioning\nDriver" as OPD
participant "Locker\n unit" as LU

actor "Attacker" as Att #red

activate CCU
note over CCU: in process of delivery

loop go to user until destination reached

alt
Att     -[#red]> PU: position control
note over PU #red: ignore drivers' data
else
Att     -[#red]> OPD: position control
OPD     -[#red]> PU:       invalid position
note over PU #red: use data from tampered driver
end

PU      <-[#red]> CCU:     invalid current position
note over CCU #red: going not to\n the desired position
CCU     -[#red]> MCU:      invalid target driving\n speed & direction

else try open locker not in destination

CCU     -[#red]> LU:      open locker
note over CCU #red: successfully opened because\nthe location is valid

end

deactivate CCU


@enduml