@startuml
!pragma teoz true
'autonumber

actor "Warehouse manager" as WH
participant "Authentication\n service" as AS
participant "Fleet management\n service" as FMS
participant "Communication\n service (x2)" as CS
participant "Central control\n unit" as CCU
WH     -> FMS: new task
FMS     -> CS: new task
&CS     -> CCU

activate CCU

alt all messages dropped

CCU    --> CS:      delivery started
note over CS #red: do not send notification to fms

FMS     -> CS: new task
&CS     -> CCU
note over CCU #red: task ignored

CCU    --> CS:      already in progress
note over CS #red: do not send notification to fms

note over FMS #red: got unknown state of robot

else end messages dropped

CCU    --> CS:      delivery started
&CS    --> FMS
note over FMS: ACK
CCU    --> CS:      delivery ended
note over CS #red: do not send notification to fms

WH     -> FMS: new task
note over FMS #red: no more idle robots left\n however they are
FMS     --> WH: task could not be done

end

deactivate CCU

@enduml