@startuml
!pragma teoz true
'autonumber

participant "Fleet management\n service" as FMS
participant "Central control\n unit" as CCU

FMS -> CCU: new task
activate CCU

note over CCU: started
CCU --> FMS: ok

note over FMS #red: notification ignored

FMS -[#red]> CCU: new task
note over CCU: another task in progress
CCU --> FMS: already running

note over FMS #red: last task lost and won't run

deactivate CCU

@enduml