@startuml
!pragma teoz true
'autonumber

participant "Central control\n unit" as CCU
participant "Motion control\n unit" as MCU
participant "Positioning\n unit" as PU
actor "Attacker" as Att #red

activate CCU
note over CCU: in process of delivery

loop go to user until destination reached

PU      -> CCU:     current position
CCU     -> MCU:     valid target driving\n speed & direction

&Att     -[#red]> MCU: control

note over MCU #red: send attacker's\n commands to motors
end

note over CCU #red: arrived at unknown point =>\n  robot lost physically

deactivate CCU


@enduml