@startuml
!pragma teoz true
'autonumber

actor "Attacker" as Att #red
participant "Fleet management\n service" as FMS
participant "Communication\n service (srv)" as CS0
participant "Communication\n service (rob)" as CS1
participant "Central control\n unit" as CCU

FMS     -> CS0:      new task (address+sig + enc pin)

note over CS0 #red: details changed
CS0      -[#red]> Att:     PIN
note over Att #red: pin encryption broken

CS0      -[#red]> CS1:     task data
note over CS0,CS1 #red: MITM. Task data stolen/altered

note over CS1 #red: details changed

activate CCU

alt task was changed
CS1      -[#red]> CCU: task with attacker's pin and/or address

alt attacker installed his keys to robot
note over CCU #red: go to attacker's address and open locker
else "else"
note over CCU: task ignored due to validation failed
end

else for OLD architecture
CS1      -[#red]> CCU: task with attacker's pin and address
note over CCU #red: go to attacker's address and/or open locker

end alt


deactivate CCU
deactivate FMS


@enduml