@startuml
!pragma teoz true
'autonumber

actor "Warehouse manager" as WH
participant "WEB market" as STOR
participant "Fleet management\n service" as FMS
participant "Authentication\n service" as AS
participant "Central control\n unit" as CCU
participant "Motion control\n unit" as MCU
participant "Positioning\n unit" as PU
participant "Odometer Positioning\nDriver" as OPD
participant "Sensors\n unit" as SU
participant "Locker\n unit" as LU
participant "Human-machine\n interface unit" as HMI
actor "User" as User

User    -> STOR:      new order

WH      -> STOR:     new delivery request
activate FMS
STOR    -> FMS:     signed delivery task
activate AS
FMS     -> AS:      create PIN
AS      -> User:    plain PIN
AS     --> FMS:     encrypted PIN
deactivate AS
FMS     -> CCU:      new task (address+sig + encrypted pin)

activate CCU

CCU    --> FMS:      delivery started

CCU     -> CCU:     validate address signature
CCU     -> CCU:     decrypt pin
opt task invalid OR adderess signature invalid
CCU    --> FMS:      unable to start task
end opt

loop go to user until destination reached

MCU     <-> OPD:      odometry request & data reply
OPD     <-> PU:       position request & data reply
PU      <-> CCU:      position request & data reply
CCU     -> MCU:      target driving\n speed & direction
MCU     -> MCU:       apply restrictions

end


CCU     -> MCU:     stop motors


loop unill find human
PU      <-> SU:      current position request & data reply
end

SU      -> CCU:     human detected
activate CCU #DDDDDD


loop until code valid or attempts count ended
User    -> HMI:     plain PIN
activate HMI

HMI     -> CCU:     hashed PIN
CCU     -> CCU:     check PIN
CCU     --> HMI:     PIN status
deactivate HMI
end

alt Valid PIN supplied

CCU     -> LU:      open locker
activate LU
LU      -> LU:      locker open\nfor 5sec
LU     --> CCU:     locker closed
LU     --> CCU:     locker door closed
deactivate LU

else Maximum invalid attempts count reached

CCU    --> FMS:      user failed to enter PIN

deactivate CCU
end

loop go to warehouse until destination reached
MCU     <-> OPD:      odometry request & data reply
OPD     <-> PU:       position request & data reply
PU      <-> CCU:      position request & data reply
CCU     -> MCU:      target driving\n speed & direction
MCU     -> MCU:       apply restrictions
end

CCU     -> MCU:     stop motors

CCU     --> FMS:     delivery ended

deactivate CCU

&FMS    --> WH:     delivery ended

deactivate FMS


@enduml